#!/bin/bash

if [ $1 == "up" ]; then
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
elif [ $1 == "down" ]; then
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
fi
volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk -F : '{print substr($2, 2, length($2))*100}')

dunstify "Volume: " -i audio-volume-high-symbolic -h int:value:$volume 

